.github/CODEOWNERS
es-hangul 라이브러리의 관리 책임을 명확히 하기 위해 코드 오너(CODE OWNER)가 추가되었습니다.
이 레포지토리의 모든 코드에 대한 기본 검토자를 추가했습니다.
1. I have read the [Contributing Guide](https://github.com/toss/slash/blob/main/.github/CONTRIBUTING.md)
=> chore: 코드 오너를 추가합니다

.github/PULL_REQUEST_TEMPLATE.md
PR template에서 Contributing Guide에 다른 레포지토리의 링크가 걸려있었습니다.
이를 수정합니다.
1. I have read the [Contributing Guide](https://github.com/toss/slash/blob/main/.github/CONTRIBUTING.md)
=> chore: pr template에서 잘못된 주소가 걸려있는 링크를 변경합니다.

package.json
NPM 에 올라갈 keyword를 package.json에 추가하여, 검색에 용이하게 합니다.
1. I have read the [Contributing Guide](https://github.com/toss/slash/blob/main/.github/CONTRIBUTING.md)
=> chore: NPM 에 올라갈 keyword를 package.json에 추가하여, 라이브러리 특성을 나타냅니다.

src/utils.spec.ts
https://github.com/toss/es-hangul/pull/38 에 추가된 `hasValueInReadOnlyStringList`, `hasProperty`의 테스트 코드를 추가했습니다. 이를 통해 추가된 함수들의 기능과 목적을 전달하는데 도움이 될 것 같습니다 🤗
=> test: Added test code for the hasValueInReadOnlyStringList and hasProperty utility functions

.changeset/config.json
아래 사진과 같은 changesets 에러를 제거합니다
=> chore: changesets의 config 불필요한 fixed필드를 제거합니다

package.json, tsup.config.ts
tsup 옵션을 CLI 대신 config 파일로 관리합니다
옵션을 type-safety하게 관리할 수 있고 향후 추가/수정에 용이합니다
=> chore: tsup.config.ts 추가

.changeset/config.json, package.json, yarn.lock
@changesets/changelog-github를 활용해 CHANGELOG에 기여자의 GitHub 유저이름이 포함되면 기여자에게 동기부여에 도움이 될 수 있다고 생각합니다.
기여자의 이름이 포함되지 않고 버저닝만 됩니다
1. 앞으로 Thanks! GitHub Username ! 이 포함됩니다
2. 해당 PR로 링크도 추가됩니다. 
3. I have written documents and tests, if needed.
=> ci(*): @changesets/changelog-github를 추가합니다

.github/CODEOWNERS
CODEOWNER의 문법을 올바르게 합니다.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax
`*` 를 사용해서 모든 파일에 대한 CODEOWNER로 명시합니다. 
=> chore(*): update CODEOWNER

src/disassembleCompleteHangulCharacter.spec.ts, src/disassembleCompleteHangulCharacter.ts
현재 `disassembleCompleteHangulCharacter` 함수에서 실패에 대한 테스트 케이스가 없어서 추가했습니다..!
작업하면서 함수에 대한 주석도 추가했습니다.
=> test: disassembleCompleteHangulCharacter 테스트 추가

.changeset/poor-impalas-train.md, docs/src/pages/docs/api/josa.en.mdx, docs/src/pages/docs/api/josa.ko.mdx, docs/src/pages/docs/api/josa.pick.en.mdx, docs/src/pages/docs/api/josa.pick.ko.mdx
josa 및 josa.pick 문서에 실행해볼 수 있는 데모를 추가합니다.
https://github.com/user-attachments/assets/14935562-cb20-4823-b80f-ab9571a68117
https://github.com/user-attachments/assets/ecfe814e-61ea-4286-82c5-e51a890a9f1d
=> docs: josa 및 josa.pick 문서에 데모 추가

src/standardizePronunciation/index.ts
- 대문자 `I`는 숫자 `1`이나 소문자 `l`과 혼동될 수 있음
- 일반 변수의 네이밍 컨벤션은 카멜케이스를 따름
위의 이유로 변수명을 변경합니다.
=> chore: rename `I` => `index`

src/hasBatchim.spec.ts
=> fix: deserialize를 잘못 Import해서 lint 오류가 나는것을 해결합니다.

.changeset/weak-walls-sniff.md
=> fix: 잘못된 changeset md 파일을 수정합니다.

.changeset/config.json
=> ci(changeset): update config.json

docs/src/pages/docs/api/canBe.ko.mdx
=> fix(docs): 문서에 잘못된 사용해보기 예시를 수정합니다.

package.json
changeset를 통한 배포 에러를 해결하기 위해서 PR 남겨요
=> chore: resolve changeset cli error

package.json
=> chore: 2.2.0 publish

docs/src/pages/docs/introduction.ko.mdx
안녕하세요, `introduction.ko.mdx` 문서 상에 인라인 코드 블럭 및 마침표가 제대로 반영되어 있지 않은 부분이 있어 수정하였습니다.
=> docs: fix typos in `introduction.ko.mdx`

.github/workflows/release.yml
* .github/workflows/release.yml 
* actions/setup-node의 node-version을 node-version-file이 .nvmrc인 것으로 변경합니다.
=> chore: actions/setup-node의 node-version를 node-version-file로 변경

README-en_us.md, README.md
README.md 파일에 hangul-js에 관한 감사의 문구를 작성합니다. 
hangul-js의 유지보수를 중단함에 따라 es-hangul로 신규 유저를 부스팅하고자 합니다.
=> chore: README.md 파일에 hangul-js에 관한 감사의 문구를 작성합니다.

src/convertHangulToQwerty/convertHangulToQwerty.spec.ts
```convertQwertyToHangul``` =>``` convertHangulToQwerty```
=> test: 테스트 설명을 실제 기능에 맞게 수정합니다.

docs/src/pages/docs/api/convertQwertyToHangul.ko.mdx, docs/src/pages/docs/api/numberToHangul.ko.mdx, docs/src/pages/docs/api/seosusa.en.mdx
=> docs: Fix typos in documentation 

src/convertHangulToQwerty/convertHangulToQwerty.ts
- convertHangulToQwerty TSdocs에 example 을 추가합니다.
=> chore: convertHangulToQwerty 함수 TSdocs에 example을 추가합니다.

docs/src/pages/index.en.mdx, docs/src/pages/index.ko.mdx
=> fix: API 문서 진입점 수정

docs/src/pages/docs/_meta.en.json, docs/src/pages/docs/_meta.ko.json, docs/src/pages/docs/advantages/benchmark.ko.mdx, docs/src/pages/docs/advantages/reliability.ko.mdx, docs/src/pages/docs/advantages/type-support.ko.mdx, docs/src/pages/docs/api/core/josa.en.mdx, docs/src/pages/index.en.mdx, docs/src/pages/index.ko.mdx
- 사이드바에서 한국어 버전일 때 영어로 표시된 `advantages`와 `migration`을 한국어로 추가했고, `benchmark`, `reliability`, `type support`도 한국어로 수정했어요.
- 사이드바에서 영어 버전일 때 일관성을 위해 `advantages`와 `migration`을 대문자로 추가해줬어요.
- 소개 문서에서 `if`문의 가독성 향상을 위해 띄어쓰기를 추가했어요.
- `josa.ko.mdx`에서와 동일하게 `josa.en.mdx`에서 주요 조사들을 인라인 코드 처리 해줬어요.
=> docs: 가독성과 일관성 향상을 위한 문서 수정

.github/workflows/broken-link-checker.yml, .github/workflows/codecov.yml, .github/workflows/release.yml
=> ci(.github/workflows): 'actions/checkout', 'actions/setup-node', 'codecov/codecov-action' v5로 업데이트
