toss/es-hangul

- .changeset/smooth-tips-yawn.md
- src/_internal.ts
- src/removeLastHangulCharacter.spec.ts
- src/removeLastHangulCharacter.ts
인자로 받은 한글 문자열에서 마지막 한글 문자 하나를 제거하여 반환하는 `removeLastHangulCharacter` 함수를 추가합니다.
```ts
removeLastHangulCharacter('안녕하세요 값') // '안녕하세요 갑'
removeLastHangulCharacter('프론트엔드') // '프론트엔ㄷ'
removeLastHangulCharacter('일요일') // '일요이'
```
이 함수는 개별적으로 사용되기도 하겠지만, https://github.com/toss/es-hangul/issues/18 에서 제안된 `assemble` 함수의 연음법칙을 구현할 때도 사용됩니다.
> feat: removeLastHangulCharacter 추가

- src/josa.spec.ts
- src/josa.ts
`josaPicker` 함수의 `word` 매개변수가 빈 문자열일 경우 발생할 수 있는 런타임 오류를 방지하기 위한 로직을 추가했습니다.
매개변수 `word`의 길이가 0(`""`)일 때 첫 번째 조사를 반환`(이/가 중 이)`하여 undefined에 접근하는 경우를 제거는 것으로 런타임 에러를 방지합니다.
추가적으로 `josa.ts`파일에서 불필요한 `non null assertion` 연산자를 제거했습니다.
이 외 배열의 요소에 접근할 때 `non null assertion`을 붙여준 경우를 종종 발견했습니다.
```ts
// utils.ts의 hasBatchim 함수
const lastChar = str[str.length - 1]!;
// disassembleCompleteHangulCharacter.ts의 반환 값
HANGUL_CHARACTERS_BY_FIRST_INDEX[firstIndex]!
```
타입스크립트에서 배열이나 문자열에 인덱스를 사용하여 접근할 때, 해당 인덱스의 값이 존재한다고 가정하기 때문에 `non null assertion`이 아무 역할도 하지 못하는 걸로 알고 있습니다.
그럼에도 이처럼 `non null assertion`을 붙여주는 의도에 대해서 여쭤보고 싶습니다!
감사합니다.
> fix: prevent runtime error in josaPicker when word is empty string

- .changeset/kind-pianos-thank.md
- src/chosungIncludes.spec.ts
- src/chosungIncludes.ts
#41 에서 발견한 '공백이 포함된 초성 검색 시 예상치 못한 false 반환 문제'를 공백 포함 입력도 정상적으로 처리하도록 수정했습니다.
- 공백을 포함한 초성 입력시에도 정상적으로 작동하도록 수정
- 공백을 포함한 초성 입력시에도 정상적으로 작동하는지 체크하기 위한 테스트 케이스 추가
> fix: Handle spaces in initialConsonants search inputs properly

- .github/workflows/codecov.yml
- codecov.yml
- package.json
- vitest.config.mts
- yarn.lock
close #63 
1. Codecov GitHub bot을 추가해주세요 https://github.com/apps/codecov
이제부터 이렇게 comment로 변경사항을 체크하고 목표 테스트 커버리지(90%로 설정해둠(목표: 100%, threshold: 10%))가 넘지 않으면 github status check에서 x로 막게 됩니다. 기여자도 테스트코드를 작성하기 위한 동기부여를 더 받을 수 있고 메인테이너도 쉽게 해당 변경으로 인한 테스트 커버리지를 빠르게 파악할 수 있게 됩니다
2. codecov에 organization과 이 레포지토리가 등록되야 해요
이 PR이 머지되면 설정이 되면서 커버리지를 트래킹하게 됩니다.
3. 머지전에 업로드용 CODECOV_TOKEN추가가 필요해요
업로드를 위해 토큰이 필요합니다
5. I have written documents and tests, if needed.
> ci(codecov): upload coverage

- .changeset/young-bears-double.md
- src/convertQwertyToHangulAlphabet.ts
- src/disassembleCompleteHangulCharacter.ts
- src/removeLastHangulCharacter.ts
기존 코드를 보다가 일부 코드 및 오타를 수정하였습니다.
1. `convertQwertyToHangulAlphabet` 함수가 반환하는 문자열은 `iterable`이기 때문에 `전개 연산자(...)`에 활용 될 수 있습니다. 현재 코드만 봤을 때 `split('')`을 통해 한번 더 배열로 변환 하는 것은 불 필요하지 않을까 생각합니다🙏 cc. @99mini 
```tsx
const str = "프론트엔드";
const arr = ["프", "론", "트", "엔", "드"];
console.log([...str]); // [ '프', '론', '트', '엔', '드' ]
console.log([...arr]); // [ '프', '론', '트', '엔', '드' ]
console.log([...str.split('')]); // [ '프', '론', '트', '엔', '드' ]
```
2. 더 이상 타입 에러를 발생시키지 않기 때문에 `Non-null assertion operator(!)`를 제거했습니다!
3. disassembedGroups -> disassembledGroups 오타 수정
> fix: convertQwertyToHangul split 및 Non-null assertion operator 제거, 네이밍 오타 수정

- README-en_us.md
- README.md
리드미 문서 내 URL의 상대경로를 절대 경로로 수정하여
외부 경로([es-hangul npm](https://www.npmjs.com/package/es-hangul) 등)에서 `CONTRIBUTING.md`, `README.md`, `README-en_us.md`등의 파일에 접근가능하도록 수정하였습니다.
> docs(README.md, README-en_us.md): 리드미 내의 링크 수정

- src/chosungIncludes.spec.ts
- src/hangulIncludes.spec.ts
- src/utils.spec.ts
[Issue] 테스트코드 리팩터링 #79
- 테스트코드의 관심사에 따라 describe를 그룹화 하였습니다.
```ts
describe('chosungIncludes', () => {
it('should return true when "ㅍㄹㅌ" is entered for searching "프론트엔드"', () => {
expect(chosungIncludes('프론트엔드', 'ㅍㄹㅌ')).toBe(true);
});
it('should return true when "ㅍㄹㅌ" is entered for searching "00프론트엔드"', () => {
expect(chosungIncludes('00프론트엔드', 'ㅍㄹㅌ')).toBe(true);
});
it('should return false when "ㅍㅌ" is entered for searching "프론트엔드"', () => {
expect(chosungIncludes('프론트엔드', 'ㅍㅌ')).toBe(false);
});
it('should return true when "ㅍㄹㅌㅇㄷㄱㅂㅈ" is entered for searching "프론트엔드 개발자"', () => {
expect(chosungIncludes('프론트엔드 개발자', 'ㅍㄹㅌㅇㄷㄱㅂㅈ')).toBe(true);
});
// ...codes
});
```
```ts
import { chosungIncludes } from './chosungIncludes';
describe('chosungIncludes', () => {
describe('초성이 포함되어있다고 판단되는 …
```
> test: 테스트 관심사에 따른 describe 세분화

- src/utils.ts
`utils.ts`의 `canBeJungsung`과 `canBeJongsung` 함수 주석에 example이 다 `canBeChosung`으로 나온 오류를 수정했습니다.
> docs: fix copy-paste error for `canBeJungsung` and `canBeJongsung`.

- .changeset/large-keys-lick.md
- .circleci/config.yml
- package.json
- yarn.lock
publishConfig의 불필요한 필드를 제거합니다
publint를 통해 package.json lint를 합니다
publint는 https://publint.dev/ 패키지가 잘 퍼블리싱되고 있는지 린팅하는 툴입니다.
1. 웹사이트에서 배포된 패키지의 package.json이 잘 정의되어있는지 체크합니다.
2. cli로 ci에 사용해 안정성을 높일 수 있습니다.
3. TanStack Query 등 사용량이 많은 패키지들에서 안정성을 위해서 사용하고 있습니다.
아래 publint에서 제공되는 링크로 es-hangul@1.3.3의 package.json의 제안사항을 확인할 수도 있습니다
https://publint.dev/es-hangul@1.3.3
- publint cli(`yarn publint`)로도 확인할 수 있게 스크립트 필드에 추가했습니다. 이를 활용해 ci에서도 항상 체크됩니다.
- publint로 체크
- type필드 누락
- publintConfig필드의 불필요한 필드
- exports필드에서 import, require시 바라볼 타입스크립트 파일을 각각 index.d.mts, index.d.ts로 지정되도록 변경
- 앞으로도 build 설정 파일(tsup)의 변경으로 달라질 때 publint가 ci에서 배포전에 잡아주게 됩니다
- https://github.com/TanStack/query/pull/5528
- https://github.com/TanStack/query/blob/main/package.json#L73
1. I have read the [Contributing …
> ci(package.json): lint by publint

- .changeset/chatty-forks-admire.md
- .circleci/config.yml
- package.json
- yarn.lock
#93 을 먼저 머지하고 update branch 후 이 PR을 머지하면 ci에러도 자연히 해결됩니다
Arethetypeswrong이라는 Tool for analyzing TypeScript types of npm packages 를 사용합니다.
이 툴을 사용하면 라이브러리의 예비 사용자의 각 node.js 환경 별로 TypeScript를 사용하는 것에 문제가 없도록 ci에서 체킹할 수 있습니다.
https://arethetypeswrong.github.io/?p=es-hangul%401.3.3
- ci에서 앞으로 체크하게 됩니다.
- AS-IS의 이미지에서 나오는 문제는 https://github.com/toss/es-hangul/pull/93에서 자연히 해결됩니다. 따라서 #93 을 먼저 머지하고 이 PR을 머지하면 ci도 자연히 해결됩니다
- https://github.com/TanStack/query/pull/7119
> ci(TypeScript): lint by arethetypeswrong

- README-en_us.md
- README.md
```tsx
import { chosungIncludes } from 'es-hangul';
const searchWord = '라면';
const userInput = 'ㄹㅁ';
const result = chosungIncludes(searchWord, userInput);
```
```tsx
import { chosungIncludes } from 'es-hangul';
const searchWord = '라면';
const userInput = 'ㄹㅁ';
const result = chosungIncludes(searchWord, userInput); // true
```
> docs: README 파일에 있는 chosungIncludes 예시의 결과 추가

- src/utils.spec.ts
`src/utils.spec.ts`의 `hasBatchim`함수의 테스트 케이스를 보강하였습니다.
AS-IS
TO-BE
> test: utils의 테스트 케이스를 보강하여 uncovered line을 개선합니다

- docs/src/components/introduction/Adopters.tsx
1. Adopters 컴포넌트의 div 태그의 스타일 작성법을 다른 컴포넌트들과 동일하게 tailwindcss로 변경하였습니다
2. Image 태그에 올바르지 않게 적용된 props를 수정하였습니다.
**Image 태그에 DOM element가 지원하지 않는 darkSrc 속성이 적용됨.**
**eslint rule 중 하나인 [jsx-a11y/alt-text](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/1be7b709eececd83f1d5f67a60b2c97cfe9a561d/docs/rules/alt-text.md)로 인해 `alt` prop을 컴포넌트에 명시해야 함.**
alt 값을 굳이 명시하고 싶지 않다면 eslint rule 설정을 변경하는 것도 선택지 중 하나인 것 같습니다.
4. I have written documents and tests, if needed.
> fix: Adopters 컴포넌트를 수정합니다

- src/removeLastHangulCharacter.spec.ts
- src/removeLastHangulCharacter.ts
`removeLastHangulCharacter()` 사용 시 마지막 문자가 받침 없이 이중모음으로 끝나는 경우에 대한 테스트를 추가했으며, 해당 함수의 `@example` 내역에 이중모음에 대한 예시를 함께 추가했습니다.
`ISO/IEC 9555`를 기반으로 제정된 [국가 표준 키보드 한글 레이아웃](https://standard.go.kr/streamdocs/view/sd;streamdocsId=72059311543363201)에서는 `'ㅗ', 'ㅜ', 'ㅡ'` 에 대한 이중모음에 대해 2회 입력을 지정합니다.
```text
ex ) 'ㅘ', 'ㅙ', 'ㅚ', 'ㅝ', 'ㅞ', 'ㅟ', 'ㅢ'
```
예를들어, `'전화'`의 `'ㅘ'`는 `'ㅗ', 'ㅏ'` 로 2회 입력이 이루어지는 이중모음이므로 `removeLastHangulCharacter('전화')` 시, `'전호'` 가 반환되어야 합니다.
</br>
한편, 이중모음 중 [국가 표준 키보드 한글 레이아웃](https://standard.go.kr/streamdocs/view/sd;streamdocsId=72059311543363201) 에서 단일키 입력을 허용하는 모음들이 있습니다. 대표적으로 `'ㅐ', 'ㅔ'` 와 `shift` 를 활용한 `'ㅒ', 'ㅖ'` 가 있습니다. 
> 해당 이중모음이 단일키 입력이 가능한 이유는, 자주 사용하는 이중 모음이기 때문이라 합니다.
예를들어, `'신세계'`의 `'ㅖ'`는 단일키 입력이 가능한 이중모음이므로 `removeLastHangulCharacter('신세계')` 시, `'신세ㄱ'` 가 반환되어야 합니다. …
> test : removeLastHangulCharacter 에 대한 테스트 추가

- .changeset/sixty-clouds-repeat.md
- src/chosungIncludes.ts
- src/constants.ts
- src/removeLastHangulCharacter.spec.ts
- src/removeLastHangulCharacter.ts
- src/utils.ts
정규식 효율개선, 불필요한 계산의 생략을 했습니다.
각각의 commit 메세지를 참조해주세요.
- [v] I read and included theses actions below
> fix: 코드 효율 개선

- src/_internal/index.spec.ts
`_internal/index.ts`에 정의된 기능들에 대해 테스트 코드를 작성합니다.
**테스트 작성전**
**테스트 작성후**
> test: internal 테스트 코드를 작성합니다

- src/_internal/hangul.spec.ts
- src/_internal/hangul.ts
#106 이슈에서 제안한 "한글 문자열"만을 다루기 위한 내부 함수를 구현합니다.
한글 문자열임을 보장하기 위해 상황에 따라 검증, assert, parsing 기능을 제공합니다.
- 검증(validation): `isHangul`
- assert: `assertHangul`
- parsing: `parseHangul`, `safeParseHangul`
** "한글 문자열"에 대한 정의는 [다른 이슈](https://github.com/toss/es-hangul/issues/41#issuecomment-2062870608)를 참고해 "공백포함"인 경우를 생각했습니다.
`parsing`은 유저 입력같이 런타임 데이터를 주로 다루는 함수에서 사용될 것으로 기대합니다.
- 알수없는 입력값 string 타입을 한글 문자열로 parsing하여 사용
example)
```ts
export function hangulIncludes(x: string, y: string) {
const parsedHangulX = safeParseHangul(x)  
const parsedHangulY = safeParseHangul(y)
if( !(parsedHangulX.success && parsedHangulY.success) ){
return false
}
// 한글 문자열로 파싱 후 disassemble
const disassembledX = disassembleHangul(parsedHangulX.data);
const disassembledY = disassembleHangul(parsedHangulY.data);
// …
```
> feat: 한글 문자열에 대한 검증, assert, parsing 함수를 구현합니다.

- .changeset/famous-cheetahs-sneeze.md
- docs/src/pages/docs/api/amountToHangul.en.md
- docs/src/pages/docs/api/amountToHangul.ko.md
- src/amountToHangul.spec.ts
- src/amountToHangul.ts
- `amountToHangul`의 함수명만 본다면 `number | string` 모두 변환가능하다고 인식될 수 있습니다.
- 기존 `string`만 가능하던 변환을 `number`로도 가능할 수 있도록 확장했습니다.
- 소숫점에도 대응 가능할 수 있도록 기능을 확장했습니다.
- 줄바꿈 등을 수정하여 가독성을 향상했습니다.
```ts
amountToHangul('15,201,100'); // '일천오백이십만천백';
amountToHangul('120,030원'); // '일십이만삼십' - 숫자 외 문자 무시
amountToHangul('392.24'); // '삼백구십이' - 소수점 무시
```
```ts
amountToHangul('15,201,100'); // '일천오백이십만천백'
amountToHangul('120,030원'); // '일십이만삼십'
amountToHangul('12345.6789'); // '일만이천삼백사십오점육칠팔구'
amountToHangul(15_201_100); // '일천오백이십만천백''
```
> fix: amountToHangul이 소수점, 숫자도 대응할 수 있도록 수정

- .changeset/wild-cows-juggle.md
- src/index.ts
> fix: 패키지가 노출하는 인터페이스를 명확히 하기 위해 index.ts를 named export로 수정합니다

- docs/src/pages/docs/api/acronymizeHangul.en.mdx
- docs/src/pages/docs/api/acronymizeHangul.ko.mdx
`acronymizeHangul` 문서에서 실제 시그니처와 일치하지 않는 부분을 수정합니다.
> docs: acronymizeHangul 리턴 타입 표기 수정

- src/_internal/hangul.spec.ts
- src/combineHangulCharacter.spec.ts
[https://github.com/toss/es-hangul/pull/135](https://github.com/toss/es-hangul/pull/135)
에러를 테스트할때 `assert.throws`, `toThrowError` 대신 일관되게 `toThrowError` 메서드를 사용합니다.
> Fix: 일관된 toThrowError 메서드 사용

- .eslintrc.js
- package.json
- yarn.lock
related with #121 
일관된 이름 짓기 규칙를 만드는 것 뿐 아니라 eslint룰로 체크해서 방지하면 미연에 문제를 방지할 수 있을 것 같아요
> chore(eslint): 의도치 않은 naming을 제거하기 위해 cspell 추가

- .eslintrc.js
- cspell.json
- cspell eslint 설정은 더이상 에러가 아닙니다.
- cspell 단어 설정은 이제 eslint 설정이 아닌, cspell.json 에서 일원화 합니다. (vscode extension + eslint)
> chore: cspell.json 으로 설정을 변경합니다.

- tsconfig.json
eslintrc의 parseOptions.project 값에 의해 vitest.config.mts 파일을 include 해야 합니다.
inlcude에 파일 경로를 추가할 시 tsconfig의 설정이 적용되어 다음과 같은 오류가 발생합니다.
tsconfig의 `resolveJsonModule` 옵션을 활성화하여 해결하였습니다.
> fix: vitest ESLint parsing error

- docs/src/pages/docs/api/canBe.en.md
- docs/src/pages/docs/api/canBe.ko.md
- docs/src/pages/docs/api/getChoseong.en.mdx
- docs/src/pages/docs/api/getChoseong.ko.mdx
- docs/src/pages/docs/api/hasBatchim.en.mdx
- docs/src/pages/docs/api/hasBatchim.ko.mdx
기존에는 아래와 같이 파스칼 케이스로 나와있었는데 카멜케이스로 나오도록 수정합니다
- CanBe
- HasBatchim 
- getChoseong
> docs: API 메뉴트리에서 함수명이 카멜케이스로 나오도록합니다

- .changeset/six-clocks-matter.md
- docs/src/components/Sandpack/Sandpack.tsx
- docs/src/components/introduction/Adopters.tsx
- docs/src/components/theme-mode/ThemeMode.tsx
- docs/src/hooks/use-is-dark-mode.ts
- docs/theme.config.tsx
**useIsDarkMode의 초기값을 undefined로 설정**합니다. 
기존의 방식은 다크 모드를 인식하기 전에 초기값 false를 노출시켜 오해를 일으킬 수 있다고 보았습니다. 
따라서 undefined일 때는 null을 반환하는 방식으로 구현하여 모드가 제대로 인식되기 전에는 이미지가 노출되지 않도록 변경하였습니다.
예를 들어 화이트 모드일 경우, 
1)다크 이미지가 불필요함에도 이미지를 가져오고 있고 
2)이미지 변경이 일어나 깜박임 현상이 발생했습니다. 
따라서 초기값을 undefined로 설정하여 불필요한 이미지를 가져오는 것을 없애고 이미지 노출을 막아 깜박임 현상을 해결하였습니다.
**[변경 전]**
**[변경 후]**
> fix: useIsDarkMode의 초기값을 undefined로 설정

- README-en_us.md
- README.md
- docs/src/pages/docs/introduction.en.mdx
- docs/src/pages/docs/introduction.ko.mdx
- docs/src/pages/index.en.mdx
- docs/src/pages/index.ko.mdx
영문서와 한글 문서의 주석을 일치 시키고자 합니다.
기존 문서는 다음과 같습니다. 
``` ts
// en 
if (result === userInput) {
// do something
}
```
``` ts
// ko
if (result === userInput) {
// 일치한다면 if문이 실행
}
```
ko 문서의 주석은 es-hangul과는 관련없는 js 언어에 대한 설명이란 생각이 듭니다. 
다음과 같이 수정하였습니다.
- if 문의 조건에 대한 설명 추가
- if 문 내부에 주석 대신 something()으로 변경
``` ts
// en
// Check if the 'choseong' of the search word match the user input
if (result === userInput) {
something()
}
```
``` ts 
// ko
// 검색어의 초성과 사용자 입력 초성이 일치하는지 확인
if (result === userInput) {
something()
}
```
만약 if 문의 조건에 대한 설명이 필요 없다고 생각되신다면, 다음과 같이 `something()`으로 통일하는것은 어떨까요? 
> en의 `// do something`으로 통일하는것은 한글 문서에서는 적절하지 않은 생각이 들었습니다.
``` ts 
if (result === userInput) {
something()
}
```
혹은 더 좋은 의견 있으시다면, 말씀 해주시면 반영하겠습니다. 감사합니다. :)
1. I have read the [Contributing …
> docs: 영문과 한글이 일치하지 않는 문제 수정

- src/disassembleCompleteCharacter/disassembleCompleteCharacter.spec.ts
Fixed the issue where parentheses were missing in the function calls of 'disassembleCompleteCharacter' in the test code.
> test: Fix missing parentheses in function call

- .github/workflows/broken-link-checker.yml
I have updated the workflow to use environment variables to avoid code injection vulnerability. Please set up the environment variable accordingly.
I found a code injection vulnerability in the es-hangul GitHub workflow process, which allows users to inject arbitrary OS commands during the workflow process.
The broken-link-checker.yml file uses variable interpolation in the run step with a user-controlled variable (github.event.inputs.url), which inputs user-data (untrusted) directly in a shell command. If an attacker can control or manipulate the github.event.inputs.url value (e.g., by submitting a malicious pull request or triggering an event with crafted input), they could inject shell commands.
**Proof of Concept (PoC):**
For ease of testing, I created a new event file which calls the …
> Update broken-link-checker.yml to avoid code injection vulnerability

- docs/src/styles/globals.css
- 공백이 포함된 폰트 이름(Toss Product Sans, Bazier Square 등)에 따옴표를 추가하여 CSS의 표준에 맞게 수정하였습니다.
- *body로 잘못 지정되어 있다고 생각하여 CSS 선택자를 body로 수정하여 불필요한 *를 제거하였습니다.
> fix: CSS 파일에서 공백이 있는 폰트 이름에 따옴표 추가 및 불필요한 * 제거

- .changeset/two-ravens-end.md
- src/susa/susa.ts
susa에 jsdoc을 추가합니다.
https://github.com/toss/es-hangul/pull/201#issuecomment-2298715354 에서 논의된 내용을 바탕으로 만들어졌어요.
Special Thanks to @BO-LIKE-CHICKEN 
> docs: susa 함수에 jsdoc을 추가합니다.

- .changeset/gorgeous-shoes-check.md
- src/josa/josa.ts
`josa`, `josa.picker` 의 리턴타입을 제네릭을 통해 개선하여 type-narrowing을 합니다.
> fix: josa 리턴 타입 보강

- docs/src/pages/docs/api/standardizePronunciation.ko.mdx
안녕하세요, `standardizePronunciation.ko.mdx` 문서를 읽다 오타를 발견하여 수정하였습니다.
`담뇨`가 올바른 표현으로 판단됩니다.
> docs: fix a typo in `standardizePronunciation.ko.mdx`

- .changeset/few-lies-give.md
- src/hasBatchim/hasBatchim.ts
다음과 같은 개선을 하였습니다.
- charCode가 한글인지를 AND로 개선하던 로직을 OR로 개선하여, 앞의 조건이 true 일 경우 뒤의 조건을 검사하지 않도록 하였습니다.
- options.only로 분기하던 if문을 switch case문으로 수정하여, options.only를 한 번의 분기만 하도록 수정하였습니다.
> chore: hasbatchim 함수의 조건문 검사 로직을 개선합니다.

- docs/src/pages/docs/advantages/type-support-table.tsx
ASIS.
TOBE.
표의 항목마다 분리된 느낌을 주어 집중도를 향상시킵니다.
> feat: type support page에 table bottom border를 추가합니다

- docs/src/pages/docs/advantages/type-support-table.tsx
ASIS.
https://github.com/user-attachments/assets/55cf0d3d-847e-4932-8388-f82dd1c08155
TOBE.
https://github.com/user-attachments/assets/d9242b54-ca16-463c-a41e-b44a640c00c1
iOS에서 동영상이 autoplay 기능을 제공할 경우 자동으로 전체화면으로 전환되는 현상을 제거합니다.
> fix: iOS에서 동영상이 자동으로 전체화면으로 전환되는 현상 제거

- src/disassembleCompleteCharacter/constants.ts
ASIS.
TOBE.
파일 내부에 구현되어 있던 `NUMBER_OF_JUNGSEONG` 상수는 `src/_internal` 경로에서 선언되어 사용되고 있습니다. 그러므로 `disassembleCompleteCharacter` 하위에 구현되어 있던 파일을 삭제합니다.
> chore: 더는 사용되지 않는 파일을 삭제하여 테스트 커버리지를 보강합니다

- src/numberToHangul/numberToHangul.spec.ts
- src/numberToHangul/numberToHangul.ts
ASIS.
TOBE.
유효하지 않은 숫자에 대한 오류 처리 로직을 추가하였습니다. 또한, 내부 로직상 9999가 넘을수가 없어 기존의 에러 던지기는 제거하였습니다.
> chore: numberToHangul 테스트 커버리지 보강

- .changeset/soft-countries-sort.md
- src/susa/susa.ts
ASIS.
TOBE.
반환 타입을 정의하기 위해 불필요하게 선언되어 있던 에러문을 제거하여 테스트 커버리지를 보강합니다.
> chore: susa 테스트 커버리지 보강

- .changeset/tender-bugs-judge.md
- docs/src/pages/docs/api/numberToHangul.en.mdx
- docs/src/pages/docs/api/numberToHangul.ko.mdx
- docs/src/pages/docs/api/numberToHangulMixed.en.mdx
- docs/src/pages/docs/api/numberToHangulMixed.ko.mdx
- src/numberToHangul/numberToHangul.spec.ts
- src/numberToHangul/numberToHangul.ts
- src/numberToHangulMixed/numberToHangulMixed.spec.ts
- src/numberToHangulMixed/numberToHangulMixed.ts
- src/seosusa/seosusa.ts
`numberToHangulMixed` 및 `numberToHangul`가 양의 정수 뿐만 아니라 소수, 음수, 무한대 또한 처리할 수 있게 수정하였습니다.
> fix: numberToHangulMixed 및 numberToHangul에 모든 number 처리

- docs/src/pages/docs/api/amountToHangul.en.mdx
- docs/src/pages/docs/api/amountToHangul.ko.mdx
related issue: #321 
영문 및 한글 문서 모두에 deprecation 경고를 추가했습니다.
함수 JSDoc의 문구를 이용했습니다.
> docs: amountToHangul 문서에 deprecated 표시

- docs/src/pages/docs/_meta.en.json
- docs/src/pages/docs/_meta.ko.json
#345 에서 `_meta.en.json`과 `_meta.ko.json`에서 trailing comma를 제거하지 않아 본 docs에 제대로 적용이 되지 않았어요. 
trailing comma를 제거함으로써 제대로 반영됩니다.
> fix: 사이드바 번역 파일에서 trailing comma 제거

- src/core/removeLastCharacter/removeLastCharacter.ts
로마자 표기법에 따르면 "성"은 `sung`이 아닌 `seong`으로 표기되어야 하므로 이에 맞게 변수명을 수정했어요.
> fix: 로마자 표기법에 의거하여 한글 자모 변수명을 수정합니다.

- src/number/seosusa/seosusa.spec.ts
seosusa 함수의 테스트 커버리지를 92.85%에서 100%로 개선했습니다. 기존에 커버되지 않았던 numberToHangul 에러 처리 로직에 대한 테스트를 추가했습니다.
- src/number/seosusa/seosusa.spec.ts에 에러 처리 테스트 케이스 추가
- vi.spyOn을 사용하여 numberToHangul 함수를 mock하고 의도적으로 에러를 발생시켜 catch 블록 테스트
- 테스트 커버리지 100% 달성
`yarn test src/number/seosusa/seosusa.spec.ts`
> seosusa 함수의 테스트 커버리지를 100%로 개선

- .changeset/tame-wolves-end.md
- src/number/numberToHangul/numberToHangul.spec.ts
- src/number/numberToHangul/numberToHangul.ts
1. `numberToHangul` 함수의 소수점 아래 변환 시 "영" 이 생략되는 문제를 수정합니다.
```
// AS-IS
console.log(numberToHangul(0.0102)); // "영점일이"
// TO-BE
console.log(numberToHangul(0.0102)); // "영점영일영이"
```
2. `numberToHangul.spec` '소수' 테스트에 `0.0102` 검증을 추가합니다
```
expect(numberToHangul(0.0102)).toEqual('영점영일영이');
```
> fix: numberToHangul 소수점 아래 변환 시 "영" 이 생략되는 문제를 수정합니다

- src/_internal/constants.ts
- src/core/canBeJungseong/canBeJungseong.ts
- src/core/combineCharacter/combineCharacter.ts
- src/core/disassembleCompleteCharacter/disassembleCompleteCharacter.ts
한국어 표기법에 맞게 **중성** 상수명을 수정했습니다. 기존 `JUNSEONGS`를 올바른 표기인 `JUNGSEONGS`로 변경하여 프로젝트 전체의 명명 일관성을 유지했습니다.
**변경 사항:**
- `constants.ts` : JUNSEONGS → JUNGSEONGS로 수정
- 프로젝트 내 다른 파일들에서는 이미 jungseong 표기를 사용 중
- 기존 CHOSEONGS(초성), JONGSEONGS(종성)과 명명 일관성 유지
- 한국어에서 중성은 "중성(中聲)"이므로 JUNGSEONG이 표준 표기
> fix: JUNSEONGS 상수명을 JUNGSEONGS로 수정
